
version: '2.1'

services:
  bank-web-service:
    build: bank-web-service/bank-web-service
    depends_on:
      mysql:
        condition: service_healthy
  bank-web-ui:
    build: bank-web-ui/bank-web-ui
    
  mysql:
    image: mysql:5.7.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60